config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :runs, except: [:index] do
    resources :run_bookings, only: [ :new, :create, :destroy, :update ]
    resources :runner_reviews, only: [ :new, :create ]
    resources :run_owner_reviews, only: [ :new, :create ]

  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search',  to: 'pages#search', as: "runs_search"
  get '/users/:id', to: 'users#show', as: "runner"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :runs
  has_many :run_bookings
  has_many :run_owner_reviews, dependent: :destroy
  has_many :runner_reviews, through: :run_bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable



  #validates :first_name, presence: true
  #validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, uniqueness: true, presence: true #, #format: { with: /\A.*@.*\.com\z/ }
  #validates :phone_number, presence: true
  #validates :language_spoken, presence: true
  #validates :birthdate, presence: true
  #validates :description, presence: true
  #validates :gender, presence: true
  #validates :pace, presence: true
  #validates :photo, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_created_runs = Run.all.where(user: @user)
  end
end

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 ">
        <img class="card-user-popside" src=" <%= image_path(@user.photo) %> ", style= "border-radius: 50%;">
      </div>
    <div class="col-xs-12 col-md-8 ">

    <div class="show-page__column col-xs-12 ">
      <h3><%= @user.first_name %> <%= @user.last_name %></h3>
      <p><span><i class="fa fa-clock-o"></i></span>    <%= @user.pace %> <em> min / km</em></p>

      <p><% 4.times do %>
      <i class="fa fa-star"></i>
      <% end %>
      </p>
      <p><%= link_to 'Edit profile', edit_user_registration_path %></p>
      </div>



    </div>
  </div>
  <div id="my_runs">
  <div class="row">
     <div class="col-md-12">
      <h2>Runs I'm Hosting</h2>
      <table class="table table-striped">
        <tr>
          <th>Run</th>
          <th>Participant</th>
          <th>Status</th>
          <th>Email</th>
          <th colspan="2">Action</th>
        </tr>

        <% @user_created_runs.each do |run| %>

            <% if run.run_bookings.present? %>
            <tr>
              <% run.run_bookings.each do |run_booking| %>
                <td> <%= link_to run.name, run_path(run) %> </td>
                <td> <%= run_booking.user.first_name %> <%= run_booking.user.last_name %> </td>
                <td> <%= run_booking.status %> </td>
                <td> <%= run_booking.user.email %> </td>
                <td> <%= form_tag run_run_booking_path(run, run_booking), method: :patch do %>
                  <%= hidden_field_tag 'user_to_approve_id', run_booking.user.id %>
                  <% if run_booking.status == "Pending" %>
                    <%= submit_tag 'Approve', class: 'btn btn-success btn-block' %>
                  <% else %>
                    <%= submit_tag 'Cancel', class: 'btn btn-warning btn-block' %>
                  <% end %>
                <% end %>
                </td>
                <td>
                <%= form_tag run_run_booking_path(run, run_booking), method: :delete do %>
                  <%= hidden_field_tag 'user_to_decline_id', run_booking.user.id %>
                  <% if run_booking.status == "Pending" %>
                    <%= submit_tag 'Decline', class: 'btn btn-danger btn-block' %>
                  <% else %>

                  <% end %>

                <% end %>
                </td>
              </tr>

              <% end %>

              <% else %>
              <tr>
                <td> <%= link_to run.name, run_path(run) %> </td>
                <td colspan="3"></td>
                <td><%= link_to 'Edit', edit_run_path(run), class: "btn btn-primary btn-block"  %></td>
                <td><%= link_to 'Delete',run_path(run), method: :delete, class: "btn btn-danger btn-block"  %></td>
              </tr>
              <% end %>
          <% end %>
        </tr>
      </table>
     </div>
  </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>Runs I'm Joining</h2>
      <table class="table table-striped">
        <tr>
          <th>Run</th>
          <th>Run host</th>
          <th>My request status</th>
          <th>Action</th>
        </tr>

        <% current_user.run_bookings.each do |run_booking| %>
        <tr>
          <td> <%= link_to run_booking.run.name, run_path(run_booking.run) %> </td>
          <td> <%= run_booking.run.user.first_name %> <%= run_booking.run.user.last_name %> </td>
          <td> <%= run_booking.status %> </td>
          <td><%= link_to 'Cancel', run_run_booking_path(run_booking.run, run_booking), method: :delete, class: "btn btn-warning btn-block" %></td>
        </tr>
      <% end %>

    </div>
  </div>
</div>