config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :runs, except: [:index] do
    resources :run_bookings, only: [ :new, :create, :destroy, :update ]
    resources :runner_reviews, only: [ :new, :create ]
    resources :run_owner_reviews, only: [ :new, :create ]

  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search',  to: 'pages#search', as: "runs_search"
  get '/users/:id', to: 'users#show', as: "runner"

end

app/views/pages/_search_bar.html.erb
<div class="button">
  <%= simple_form_for "", url: runs_search_path, :method => :get do |f| %>
  <div class="form-inline">
    <%= f.text_field :search, value: params[:search], placeholder: "City", class: "form-control" %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/pages/_search_form.html.erb
<div class="button">
  <%= simple_form_for "", url: runs_search_path, :method => :get do |f| %>
   <%= f.text_field :search, value: params[:search], placeholder: "City", class: "btn-medium" %>
   <%= f.text_field :run_distance, value: params[:run_distance], placeholder: "Running distance (km)", class: "btn-medium" %>
   <%= f.text_field :pace, value: params[:pace], placeholder: "Average pace (min/km)", class: "btn-medium" %>
    <%= f.submit "Search", class: "btn btn-primary btn-treehouse" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" >
  <div class="video">

    <%= video_tag "Weerun.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "video" %>

  </div>
  <div class="banner-content">
    <h1>WeeRun</h1>
    <h4>Find a run near you</h4>
    <%= render 'search_form' %>
  </div>
</div>

app/views/pages/search.html.erb
  <div class="search-container">
    <div id="runs" style="overflow-y: auto;">
    <div class="row">
      <%= render @runs %>
      </div>
    </div>

    <div id="map">
    </div>
  </div>


 <% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
      });
      });
  <% end %>
<% end %>