config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :runs, except: [:index] do
    resources :run_bookings, only: [ :new, :create, :destroy, :update ]
    resources :runner_reviews, only: [ :new, :create ]
    resources :run_owner_reviews, only: [ :new, :create ]

  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search',  to: 'pages#search', as: "runs_search"
  get '/users/:id', to: 'users#show', as: "runner"

end

app/models/run_booking.rb
class RunBooking < ApplicationRecord
  belongs_to :user
  belongs_to :run
  has_many :runner_reviews
end

app/controllers/run_bookings_controller.rb
class RunBookingsController < ApplicationController

  def new
    @run_booking = RunBooking.new
    @run = Run.find(params["run_id"])
  end

  def create
    @run = Run.find(params["run_id"])

    @run_booking = RunBooking.new
    @run_booking.run = @run
    @run_booking.user = current_user
    @run_booking.status = "Pending"

    if @run_booking.save!
       redirect_to run_path(@run)
    end
  end

  def update

    @user_to_approve = User.find(params[:user_to_approve_id])
    @run_booking = RunBooking.find(params[:id])

    if @run_booking.status == "Accepted"
      @run_booking.status = "Pending"
    else
      @run_booking.status = "Accepted"
    end
    @run_booking.save!

    redirect_to runner_path(current_user)
  end

  def show
    @run_booking = RunBooking.find(params[:run])
  end

  def destroy
    @run_booking = RunBooking.find(params[:id])
    @run_booking.destroy

    if params[:previous_page] == "run"
      redirect_to run_path(@run_booking.run)
    else
      redirect_to runner_path(current_user)
    end
  end


  # def approve_booking
  #   @run_booking = RunBooking.find(params[:id])
  #   @run_booking.status = "approved"
  #   @run_booking.save
  #   redirect_to run_path(@run), notice: "A booking from #{@booking.user_id} has been accepted"
  # end

private

  def set_run
    @run = Run.find(params[:run_id])

  end


def run_booking_params
    params.require(:booking).permit(:run, :user, :run_id, :runner_reviews, :run_owner_reviews, :status)
  end

end

app/views/run_bookings/_booking_form.html.erb
<!-- Modal -->
<div class="modal fade" id="booking" tabindex="-1" role="dialog" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="bookingModal"><%= @run.name.titleize %></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">

          <div class="col-xs-12 col-md-6">
            <p><b>Distance:</b> <%= @run.run_distance %>km</p>
            <p><b>Pace:</b> <%= @run.pace %>min/km</p>
            <p><b>Group size:</b> <%= @run.group_number %> people max</p>
            <p><b>Type:</b> <%= @run.incline %></p>
          </div>

          <div class="col-xs-12 col-md-6">
            <p><b>Location: </b><%= @run.location %></p>
            <p><b>Date: </b><%= @run.date_time.strftime("%d %b %Y") %></p>
            <p><b>Time: </b><%= @run.date_time.strftime("%H:%M") %></p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>

        <%= link_to "Submit Request", run_run_bookings_path(@run), method: :post, class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

app/views/run_bookings/new.html.erb
<%= render 'booking_form' %>